"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.IERC721__factory = exports.IERC165__factory = exports.ERC721Voucher__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var ERC721Voucher__factory_1 = require("./ERC721Voucher__factory");
Object.defineProperty(exports, "ERC721Voucher__factory", { enumerable: true, get: function () { return ERC721Voucher__factory_1.ERC721Voucher__factory; } });
var IERC165__factory_1 = require("./IERC165__factory");
Object.defineProperty(exports, "IERC165__factory", { enumerable: true, get: function () { return IERC165__factory_1.IERC165__factory; } });
var IERC721__factory_1 = require("./IERC721__factory");
Object.defineProperty(exports, "IERC721__factory", { enumerable: true, get: function () { return IERC721__factory_1.IERC721__factory; } });
